// Public, unauthenticated verification page. Anyone who scans a SafeVerse
// certificate QR code lands here. Looks up the real Certificate row by its
// qrToken and checks revoked/expiry status server-side.

import { db } from "@/lib/db";
import { getMissionById } from "@/lib/scenarios";

export default async function VerifyPage({ params }: { params: { certId: string } }) {
  const cert = await db.certificate.findUnique({
    where: { qrToken: params.certId },
    include: { worker: { include: { site: true } } }
  });

  if (!cert) {
    return (
      <main className="min-h-screen bg-paper text-void flex items-center justify-center px-6 py-12">
        <div className="max-w-sm w-full bg-white border border-slate-200 rounded-panel p-8 text-center shadow-sm">
          <p className="text-3xl mb-3">❓</p>
          <h1 className="text-xl font-bold mb-1">Certificate Not Found</h1>
          <p className="text-slate-500 text-sm">
            No certificate matches this code. It may have been mistyped, or the QR wasn't generated by SafeVerse.
          </p>
        </div>
      </main>
    );
  }

  const isExpired = cert.expiresAt < new Date();
  const isRevoked = cert.revoked;
  const valid = !isRevoked && !isExpired;
  const mission = getMissionById(cert.missionId);

  return (
    <main className="min-h-screen bg-paper text-void flex items-center justify-center px-6 py-12">
      <div className="max-w-sm w-full bg-white border border-slate-200 rounded-panel p-8 text-center shadow-sm">
        <p className="text-3xl mb-3">{valid ? "✅" : "⚠️"}</p>
        <h1 className="text-xl font-bold mb-1">
          {valid ? "Valid Certificate" : isExpired ? "Certificate Expired" : "Certificate Revoked"}
        </h1>
        <p className="text-slate-500 text-sm mb-6">SafeVerse Certificate Verification</p>

        <div className="text-left border-t border-slate-200 pt-4 space-y-2 text-sm">
          <Row label="Worker" value={cert.worker.name} />
          <Row label="Employee ID" value={cert.worker.employeeCode} />
          <Row label="Site" value={cert.worker.site?.name ?? "—"} />
          <Row label="Module" value={mission ? `${mission.emoji} ${mission.title}` : cert.missionId} />
          <Row label="Issued" value={cert.issuedAt.toDateString()} />
          <Row label="Expires" value={cert.expiresAt.toDateString()} />
          <Row label="Certificate ID" value={cert.qrToken} mono />
        </div>
      </div>
    </main>
  );
}

function Row({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex justify-between gap-4">
      <span className="text-slate-500">{label}</span>
      <span className={`text-right ${mono ? "font-mono text-xs" : "font-medium"}`}>{value}</span>
    </div>
  );
}
